name: auto-study

on:
  workflow_dispatch:
  
  schedule:
    - cron: 0 6 * * 3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
    
    - name: Pip requirements
      run: |
        pip3 install requests pycryptodome
         
    - name: auto study
      run: |
        python3 workflow.py <<EOF
        ${{secrets.USERNAME}}18259115126
        ${{secrets.PWD}}18259115126
        ${{secrets.PUB_KEY}}MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKf9iZkA5HEFw4zt7MRBkcmgUiz5+r5eqDOKbaurEbScmXd3ZZTtyzirqkYKRIH5mQ+8hq+Wd/pTZNXHS8L0+88CAwEAAQ==
        ${{secrets.OCR_API_KEY}}GooCgj6HftqQNoSiyGGKoDHm
        ${{secrets.OCR_SECRET_KEY}}9CpRMi26Qx81by2G1qWm2QtQaAyu6l80
        EOF
        
